name: Update Year in README

on:
  schedule:
    - cron: '0 0 1 1 *'  # Runs at midnight UTC on January 1st
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grants write permission only for this specific job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update README year
        run: |
          sed -i "s/© 2004-[0-9]\{4\}/© 2004-$(date +'%Y')/" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git commit -am "Update year to $(date +'%Y')"
          git push
